# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-6.1
packages:
- '.'
extra-deps:
  - slack-api-0.8
  - smallcheck-series-0.5.1
flags: {}

extra-include-dirs:
- /usr/local/opt/openssl/include
extra-lib-dirs:
- /usr/local/opt/openssl/lib
