# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-5.17
packages:
- '.'
extra-deps:
  - servant-0.7.1
  - servant-client-0.7.1
  - slack-api-0.8
  - string-conv-0.1.1
flags: {}

extra-include-dirs:
- /usr/local/opt/openssl/include
extra-lib-dirs:
- /usr/local/opt/openssl/lib
